name: family_space_flutter
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.1.1
  video_player: ^2.2.7
  sliding_up_panel: ^2.0.0+1
  location: ^4.3.0
  freezed_annotation: ^1.1.0
  flutter_bloc: ^8.0.0

  mapbox_gl: ^0.14.0
  shared_preferences: ^2.0.11
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.5
  freezed: ^1.1.0
  json_serializable: ^6.1.1

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/video/backdrop_720.mov
    - assets/images/
